mexca/mexca

README.md, mexca/core/utils.py, tests/core/test_utils.py
- Fixes the `TimeStepWarning` in the `create_time_var_from_step` function by calling the `warnings.warn` function (should satisfy SonarCloud)
- Adds a test for `utils.py`
- Updates the citation in the README to match the CITATION.cff file
=> Minor fixes to README and code

docs/index.rst, docs/installation.rst
This PR aims at updating the installation instruction within the documentation to reflect the readme
=> 261 update read the docs

.github/workflows/docker.yml
Fixes the container build action.
=> Fix container action

.github/workflows/release.yml, setup.cfg
Fixes the automatic upload to PyPI action on release.
=> Fix release action

mexca/text/transcription.py
Fixes the audio transcriber container.
=> Fix transcription

mexca/audio/identification.py, mexca/container.py, mexca/video.py, tests/test_audio_identification.py, tests/test_video.py
Adds exceptions for when:
- Not enought faces were detected for clustering
- No HF token was found when `SpeakerIdentifier(use_auth_token=True)`
- An invalid HF token was supplied to `use_auth_token`
- pypiwin32 was not correctly installed when calling `docker.from_env()`
=> Add exceptions

docs/getting_started.rst, docs/installation_details.rst
Adds instructions on how to authenticate to HuggingFace Hub and download gated pyannote.audio models.
Adds "Troubleshooting" section with solution to pypiwin32 install issue.
=> Update "Getting Started" and add "Troubleshooting" section

.github/workflows/docker.yml, docker/download_models.py, docker/speaker-identifier/Dockerfile
Fixes the SpeakerIdentifier Dockerfile and Docker build action to authenticate correctly to HuggingFace Hub and download the pretrained models.
=> Fix token passing in speaker identifier container build

.github/workflows/docker.yml, mexca/container.py, tests/test_container.py
Adds versioned Docker containers. Instead of using the latest tag of the component containers, the tag corresponding to the current version of mexca is used.
=> Add using versioned Docker containers

.github/workflows/docker.yml, .github/workflows/docker_release.yml, mexca/container.py, setup.cfg, tests/test_container.py
Fixes the installation for Python 3.7.
Fixes the build of the SentimentExtractor container.
Adds a GitHub actions workflow for automatically pushing containers to Docker Hub on release.
=> Fix docker build and Python 3.7 installation

.github/workflows/docker_release.yml
Fixes the automated build and push of the Docker containers to Docker Hub.
=> Fix automated docker builds

mexca/text/transcription.py, tests/test_text_transcription.py
Fixes a bug in `AudioTranscriber._get_avg_confidence()` and adds tests for it.
=> Fix bug in text confidence score calculation for zero length segments

docs/output.rst, mexca/data.py, tests/test_data.py
Fixes a bug where multiple filename columns where created in the merged feature dataset in the `Multimodal` class.
=> Fix merging data from modalities

mexca/audio/identification.py
Adds a hook to extract and display the current progress of the speaker identification.
=> Add progressbar for speaker identification

docs/getting_started.rst, docs/gpu.rst, docs/index.rst, docs/installation_details.rst, docs/introduction.rst
Adds instructions on how to install and use mexca with CUDA and GPU support.
=> Add docs for GPU support and CUDA installation

docs/docker.rst, docs/gpu.rst, examples/example_custom_pipeline_components.ipynb, examples/example_emotion_feature_extraction.ipynb
I fixed some typos that I saw when skimming the documentation
=> fix some typos in docs and bugs in examples

mexca/pipeline.py, mexca/video/extraction.py
Changes logging to only write essential steps and rephrases some logging steps.
=> Only log essential steps

mexca/container.py, tests/test_container.py
Makes the error message more informative if the connection to the docker daemon fails.
Adds a test for the error message.
=> Add more informative error message if connection to daemon fails

.gitmodules
Adds the software paper repository as a git submodule.
=> Add code and supplement for software paper

.github/workflows/build.yml, .github/workflows/docker.yml, .github/workflows/docker_release.yml, mexca/text/sentiment.py, mexca/video/extraction.py, recipes/recipe_postprocess_features.py, recipes/recipe_standard_pipeline.py
Fixes a rare bug in the tokenizer of the XLM Roberta Sentiment model by adding padding or returning `None`s as sentiment scores if the tokenization fails for an unknown reason.
Also fixes a bug in the VideoExtractor where the input for the MEFARG extractor was not sent to the correct device.
Finally, updates the standard pipeline recipe to save results after each file instead of after all files have been processed.
=> Fix runtime error in sentiment tokenizer

mexca/video/extraction.py
Fixes a bug when more faces than `num_faces` are encountered in a frame.
=> Fix bug with 'num_faces 'in face extraction

mexca/postprocessing.py, recipes/recipe_postprocess_features.py, tests/test_postprocessing.py
Adds new submodule with postprocessing functions for the merged data frame in the output:
- `split_list_columns`: Splits list columns into separate columns
- `get_face_speaker_mappings`: Calculate the optimal mapping between face and speaker labels
- `sub_labels`: Replace labels in the data frame
=> Add postprocessing functions

.readthedocs.yaml, mexca/postprocessing.py
Fixes a bug in the mapping between face labels and segment speaker labels in the `postprocessing.get_face_speaker_mapping` function.
=> Fix bug in face label speaker mapping
